### ISSUE TITLE
Dockerized build

### ISSUE THREAD

**Issue by orgildinio** [funmiayinde/shtcut-backend#413]
Hello.

This project seems very interesting and you guys doing great job. Since there is no technical documentation yet, how about update docker compose file to make setup easy?

i ran docker compose up -d but i can see only gateway running.

**Comment by funmiayinde** [comment]
Thanks, @orgildinio , you can simply do this:

`cd backend`

Then run:
`docker-compose up --build`

This will spin up all the services
